//AUTOGENERATED FILE! DO NOT EDIT!
#include "graphic_types.h"
extern const bitmap_t BITMAP_roboto_condensed_regular_18;
extern const bitmap_t BITMAP_roboto_condensed_regular_14;
extern const bitmap_t BITMAP_generalemono_a_65;
extern const bitmap_t BITMAP_generalemono_a_17;

extern const font_t FONT_roboto_condensed_regular_14;

extern const font_t FONT_generalemono_a_17;

extern const font_t FONT_roboto_condensed_regular_18;

extern const font_t FONT_generalemono_a_65;
